//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace photographyStudio.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Booking
    {
        public int BookingID { get; set; }
        public string CustomerName { get; set; }
        public string CustomerPhone { get; set; }
        public string CustomerEmail { get; set; }
        public System.DateTime BookingDate { get; set; }
        public System.TimeSpan BookingTime { get; set; }
        public Nullable<int> ServiceID { get; set; }
        public string Notes { get; set; }
        public string Status { get; set; }
    
        public virtual Service Service { get; set; }
    }
}
